version: '3.2'

services:
  nodexporter:
    image: prom/node-exporter
    deploy:
      mode: global
      restart_policy: any
        condition: any
        window: 60s
    volumes:
       "/:/host:ro,rslave"

  cadvisor:
    image: google/cadvisor
    restart: always
    ports:
      - "9094:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      restart_policy: any
        condition: any
        window: 60s

  prometeus:
    image: prom/prometheus
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        window: 60s
      placement:
        constraints:
          - node.hostname == node1.xip.io

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        window: 60s
      placement:
        constraints:
          - node.hostname == node1.xip.io

  elasticsearch1:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=test-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        window: 60s
      placement:
        constraints:
          - node.hostname == node2.xip.io

  elasticsearch2:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es02
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=test-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        window: 60s
      placement:
        constraints:
          - node.hostname == node3.xip.io

  volumes:
    esdata01:
      driver: local

    esdata02:
      driver: local
