---
version: '3.2'

services:

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - "/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "/usr/share/nginx/html/index.html:/usr/share/nginx/html/index.html"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        window: 60s
      placement:
        constraints:
          - node.hostname == swarm01
